// Backtests three day-ahead forecasting strategies against historical reanalysis
// ("actuals"), reproducing the comparison the paper makes between raw NWP,
// persistence and MOS+KF: run_model.m / conversion.m / performance_index_pv.m.
//
// There is no public feed of *past* NWP forecasts to replay, so a synthetic
// forecast is generated by perturbing the historical actual irradiance with:
//  - a fixed-but-unknown per-hour-of-day bias (models a real NWP model's
//    systematic, recurring diurnal error - e.g. underestimating morning fog
//    burn-off) - this is the persistent structure the KF is meant to learn.
//  - independent per-day/per-hour noise (models genuine weather-forecast
//    uncertainty), which is irreducible and no bias filter can remove.
// A KF that only reacts to i.i.d. noise (no persistent structure at all)
// cannot improve on the raw forecast, so the persistent-bias term is what
// makes the demo actually exercise the paper's bias-correction claim.

import { fetchHistoricalHourly } from './weather.js';
import { solarPosition } from './solarPosition.js';
import { poaIrradiance, pvPowerOutput } from './pvModel.js';
import { DailyBiasKalmanFilter } from './kalmanFilter.js';
import { performanceIndex } from './metrics.js';

function mulberry32(seed) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function gaussian(rng) {
  const u1 = Math.max(rng(), 1e-9);
  const u2 = rng();
  return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
}

// Chunk into fixed 24-hour (UTC) blocks rather than grouping by calendar date:
// Date#toDateString() reads the viewer's local timezone, which would split
// days at the wrong boundary for a site far from the browser's own timezone.
// The archive is requested with timezone=UTC, so samples start at UTC 00:00.
function groupByDay(hourlySamples) {
  const days = [];
  for (let i = 0; i + 24 <= hourlySamples.length; i += 24) {
    days.push(hourlySamples.slice(i, i + 24));
  }
  return days;
}

export async function runBacktest(system, options = {}) {
  const {
    days = 30,
    forecastBiasStd = 0.15,
    forecastNoiseStd = 0.1,
    seed = 42,
    processNoise = 1e-4,
    measurementNoise = 0.02,
  } = options;

  const hourly = await fetchHistoricalHourly(system.lat, system.lon, days);
  const dayGroups = groupByDay(hourly);
  const rng = mulberry32(seed);

  const toPower = (sample) => {
    const sun = solarPosition(sample.time, system.lat, system.lon);
    const poa = poaIrradiance(sample, sun, system);
    return pvPowerOutput({ poa, ambientTemp: sample.temp, capacityKw: system.capacityKw, losses: system.losses });
  };

  // Persistent, unknown-to-the-forecaster per-hour-of-day bias (constant for the whole backtest).
  const perHourBias = Array.from({ length: 24 }, () => 1 + gaussian(rng) * forecastBiasStd);

  const kf = new DailyBiasKalmanFilter({ numHours: 24, processNoise, measurementNoise });
  const series = [];
  let prevDayActual = null;

  for (const dayHours of dayGroups) {
    const rows = [];

    for (let h = 0; h < 24; h++) {
      const sample = dayHours[h];
      const actual = toPower(sample);

      const hourlyNoise = 1 + gaussian(rng) * forecastNoiseStd;
      const bias = perHourBias[h];
      const perturbedSample = {
        ghi: sample.ghi * bias * hourlyNoise,
        dni: sample.dni * bias * hourlyNoise,
        dhi: sample.dhi * bias * hourlyNoise,
        temp: sample.temp,
      };
      const rawForecast = toPower({ ...perturbedSample, time: sample.time });

      const persistence = prevDayActual ? prevDayActual[h] : rawForecast;
      const kfForecast = kf.correct(h, rawForecast);

      rows.push({ time: sample.time, actual, rawForecast, persistence, kfForecast });
    }

    kf.update(rows.map((r, h) => [h, r.actual - r.rawForecast]));
    series.push(rows);
    prevDayActual = rows.map((r) => r.actual);
  }

  const flat = series.flat();
  const metrics = {
    rawNwp: performanceIndex(flat.map((r) => r.rawForecast), flat.map((r) => r.actual), system.capacityKw),
    persistence: performanceIndex(flat.map((r) => r.persistence), flat.map((r) => r.actual), system.capacityKw),
    mosKf: performanceIndex(flat.map((r) => r.kfForecast), flat.map((r) => r.actual), system.capacityKw),
  };

  return { series, metrics };
}
